# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 383ec8bc802140843fafb7c8aa82c2c42396f6953ff1f6fcef2634b58b141928062fabde7efd5a57f46bfeca0bd5003c0fd28efb925ac4b07ebeac150b66067f

test:
  secret_key_base: a8f1f6f7acc34e2b26addc72104843c85c99782f385f36262ec19a64d21b99da20a01ffd348e2732107f25b0975bca96f70b54ea885f665b092a282495d4bd16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
